name: web_engine_tester

# Keep the SDK version range in sync with lib/web_ui/pubspec.yaml
environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  js: 0.6.4
  stream_channel: 2.1.1
  test: 1.22.1
  webkit_inspection_protocol: 1.0.0
  stack_trace: 1.10.0
  ui:
    path: ../../lib/web_ui
